// Jest setup file

// Mock the stream-chat module
jest.mock('stream-chat', () => ({
	StreamChat: {
		getInstance: jest.fn().mockReturnValue({
			connectUser: jest.fn(),
			disconnectUser: jest.fn(),
			channel: jest.fn().mockReturnValue({
				create: jest.fn(),
				update: jest.fn(),
				delete: jest.fn(),
				truncate: jest.fn(),
				watch: jest.fn(),
				stopWatching: jest.fn(),
				addMembers: jest.fn(),
				removeMembers: jest.fn(),
				addModerators: jest.fn(),
				demoteModerators: jest.fn(),
				inviteMembers: jest.fn(),
				acceptInvite: jest.fn(),
				rejectInvite: jest.fn(),
				queryMembers: jest.fn(),
				hide: jest.fn(),
				show: jest.fn(),
				archive: jest.fn(),
				unarchive: jest.fn(),
				pin: jest.fn(),
				unpin: jest.fn(),
				mute: jest.fn(),
				unmute: jest.fn(),
				muteStatus: jest.fn(),
				markRead: jest.fn(),
				markUnread: jest.fn(),
				sendFile: jest.fn(),
				sendImage: jest.fn(),
				deleteFile: jest.fn(),
				deleteImage: jest.fn(),
				banUser: jest.fn(),
				unbanUser: jest.fn(),
				enableSlowMode: jest.fn(),
				disableSlowMode: jest.fn(),
				sendAction: jest.fn(),
				getConfig: jest.fn(),
				sendMessage: jest.fn(),
			}),
			queryChannels: jest.fn(),
			queryUsers: jest.fn(),
			createUser: jest.fn(),
			updateUser: jest.fn(),
			deleteUser: jest.fn(),
			deactivateUser: jest.fn(),
			reactivateUser: jest.fn(),
			banUser: jest.fn(),
			unbanUser: jest.fn(),
			muteUser: jest.fn(),
			unmuteUser: jest.fn(),
			flagUser: jest.fn(),
			unflagUser: jest.fn(),
			getMessage: jest.fn(),
			updateMessage: jest.fn(),
			deleteMessage: jest.fn(),
			search: jest.fn(),
		}),
	},
}));

// Global test timeout
jest.setTimeout(10000);
